# Generated by Django 2.1.2 on 2018-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('bill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rental_ticket_or_tag_number', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('ordered_by', models.CharField(blank=True, max_length=255, null=True)),
                ('closed_flag', models.NullBooleanField(default=0)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_by', models.CharField(blank=True, max_length=255, null=True)),
                ('well_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatcher', models.CharField(blank=True, max_length=255, null=True)),
                ('field_rental_ticket', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('date_to_start_billing', models.DateTimeField(blank=True, null=True)),
                ('date_to_stop_billing', models.DateTimeField(blank=True, null=True)),
                ('last_modification_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_office_code', models.CharField(blank=True, max_length=100, null=True)),
                ('printed_flag', models.NullBooleanField(default=0)),
                ('repair_invoice_flag', models.NullBooleanField(default=0)),
                ('invoice_pre_tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('date_sent_for_signature', models.DateField(blank=True, null=True)),
                ('method_sent', models.CharField(blank=True, choices=[('EMA', 'EMAILED'), ('SAL', 'SALESMAN')], max_length=3, null=True)),
                ('person_sent_with_invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('date_signed_invoice_returned', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_void', models.NullBooleanField()),
                ('is_paid', models.NullBooleanField()),
            ],
        ),
    ]
